version: '3.8'
services:
  app:
    build: .
    platform: linux/amd64
    container_name: eoboard-app
    image: eoboard-app
    ports:
      - ${PORT}:8080
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: eoboard-db
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
