spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/eoboard
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

    hikari:
      maximum-pool-size: 4
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
#        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace